FROM eclipse-temurin:21-jre-alpine

WORKDIR /app
COPY target/ExpenseTracker-0.0.1-SNAPSHOT.jar ExpenseTracker-0.0.1-SNAPSHOT.jar

EXPOSE 8080

ENV JAVA_OPTS="-Xms256m -Xmx512m"

ENTRYPOINT ["sh", "-c", "java $JAVA_OPTS -jar ExpenseTracker-0.0.1-SNAPSHOT.jar"]
